language: emacs-lisp
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/7736123/raw | sh
  - export PATH="/home/travis/.cask/bin:$PATH"
  - export PATH="/home/travis/.evm/bin:$PATH"
  - evm install $EVM_EMACS --use --skip
  - cask
env:
  # https://github.com/cask/cask/issues/176
  # - EVM_EMACS=emacs-24.1-bin
  # - EVM_EMACS=emacs-24.2-bin
  - EVM_EMACS=emacs-24.5-bin
script:
  - emacs --version
  - make test
